# one of the following  https://cloud.yandex.ru/services#_all
services:
  dwh:
    name: Yandex Cloud DWH (Internal)
    description: Облачный DWH
  resource-manager:
    name: Yandex Resource Manager
    description: Управление ресурсами в каталогах и облаках
  storage:
    name: Yandex Object Storage
    description: Масштабируемое хранилище данных
    aliases: [s3]
  ai:
    name: Yandex SpeechKit, Yandex Translate, Yandex Vision
    description: Комплекс технологий распознавания и синтеза речи, машинный перевод, анализ изображений
    aliases: [cloudai]
  certificate-manager:
    name: Yandex Certificate Manager
    description: Управление TLS-сертификатами
  cdn:
    name: Yandex Cloud CDN
    description: Сервис CDN
  compute:
    name: Yandex Compute Cloud
    description: Виртуальные машины и диски
  container-registry:
    name: Yandex Container Registry
    description: Управление Docker-образами
  datalens:
    name: Yandex DataLens
    description: Визуализация и анализ данных
  datasphere:
    name: Yandex DataSphere
    description: Платформа для ML-разработчиков
  dns:
    name: Yandex Cloud DNS
    description: ДНС
  iam:
    name: Yandex Identity and Access Management
    description: Идентификация и контроль доступа к облачным ресурсам
  iot:
    name: Yandex IoT Core
    description: Решения для интернета вещей
  managed-kubernetes:
    name: Yandex Managed Service for Kubernetes
    description: Управление кластерами Kubernetes
    aliases: [k8s]
  kms:
    name: Yandex Key Management Service
    description: Управление ключами шифрования
  ylb:
    name: Yandex Load Balancer
    description: Сетевые балансировщики нагрузки
    aliases: [load-balancer]
  mdb:
    name: Yandex Managed Data Bases
    description: Управление базами данных
  instance-group:
    name: Yandex Instance Groups
    description: Группы виртуальных машин
  monitoring:
    name: Yandex Monitoring
    description: Сбор и визуализация метрик
  serverless:
    name: Yandex Cloud Functions
    description: Запуск вашего кода в виде функции
  api-gateway:
    name: Yandex API Gateway
    description: Cервис для управления API-шлюзами
  vpc:
    name: Yandex Virtual Private Cloud
    description: Управление сетями в облаке
  cic:
    name: Yandex Cloud Interconnect
    description: Связность между виртуальными сетями и on-premise сетями
  ydb:
    name: Yandex Database
    description: Распределённая отказоустойчивая NewSQL СУБД
  yds:
    name: Yandex Data Streams
    description: Отказоустойчивый сервис для передачи потоков данных
  ymq:
    name: Yandex Message Queue
    description: Очереди для обмена сообщениями между приложениями
  marketplace:
    name: Yandex Cloud Marketplace
    description: ''
  alb:
    name: Load Balancer API
    description: ''
  oauth:
    name: Yandex Cloud OAuth 2.0 & OpenID Connect server
    description: ''
  billing:
    name: Billing (internal)
    description: ''
  support:
    name: Support (internal)
    description: ''
  yq:
    name: Yandex Query
    description: Сервис безсерверной аналитики
  data-transfer:
    name: Data Transfer
    description: Сервис без серверного трансфера данных
  dataproc:
    name: Data Proc
    description: Управление кластерами Apache Hadoop и Apache Spark
  organization-manager:
    name: Organization Manager
    description: Управление Организациями
  vulnerability-scanner:
    name: Vulnerability Scanner (internal)
    description: Сервис сканирования образов на уязвимости
  lockbox:
    name: Yandex Lockbox
    description: Управление секретами
  managed-kafka:
    name: Yandex Managed Service for Apache Kafka
    description: Управление кластерами Apache Kafka
  managed-elasticsearch:
    name: Yandex Managed Service for Elasticsearch
    description: Управление кластерами Elasticsearch
  managed-sqlserver:
    name: Yandex Managed Service for Microsoft SQL Server
    description: Управление кластерами Microsoft SQL Server
  logs:
    name: Yandex Cloud Logs
    description: Запись, хранение, чтение и настройка логов
  logging:
    name: Yandex Cloud Logging
    description: Запись, хранение, чтение и настройка логов
  audit-trails:
    name: Yandex Audit Trails
    description: Сервис аудитных логов
  bastion:
    name: Bastion (internal)
    description: Сервис доступа по ssh
  loadtesting:
    name: Loadtesting
    description: Сервис нагрузочного тестирования
  vdi:
    name: Virtual Desktop Infrastructure
    description: Виртуальные рабочие места
  uk8s:
    name: Underlay K8S
    description: Kubernetes для железных хостов
  managed-gitlab:
    name: Yandex Managed Service for Gitlab
    description: Сервис управления Git-репозиториями
    aliases: [gitlab]
  quota-manager:
    name: Quota Manager
    description: Сервис просмотра квот и управление запросами на изменение квот
  cloudsearch:
    name: YC.CloudSearch
    description: Сервис поиска по облакам
  cloudbeaver:
    name: CloudBeaver
    description: Управление базами данных через web-интерфейс
  smart-captcha:
    name: Yandex SmartCaptcha
    description: Сервис для встраивания капчи

#DoubleCloud services
  dcnetwork:
    name: DoubleCloud Network Service
    description: Управление сетями в DoubleCloud

#Internal services
  backoffice:
    name: YC.Backoffice
    description: Внутренняя админка

  maintenance:
    name: Maintenance Service
    description: Обслуживание облачных сервисов

#Collaboration services
  tracker:
    name: Yandex Tracker
    description: Яндекс Трекер, сервис для совместной работы и организации процессов в компании

  wiki:
    name: Yandex Wiki
    description: Яндекс Вики, сервис для ведения базы знаний
